---
name: Kinetic
version: !perl/version
  qv: 1
  version:
    - 0
    - 0
    - 2
author:
  - 'Kineticode, Inc. <info@kineticode.com>'
abstract: The Kinetic enterprise application framework
license: gpl
resources:
  license: http://www.opensource.org/licenses/gpl-license.php
requires:
  Array::AsHash: 0.31
  Cache::Cache: 1.04
  Cache::Memcached::Managed: 0.14
  Class::BuildMethods: 0.1
  Class::Meta: 0.53
  Class::Meta::Express: 0.03
  Clone: 0.15
  Config::Std: 0.0.3
  DBD::Pg: 1.32
  DBD::SQLite: 1.12
  DBI: 1.5
  Data::Types: 0.06
  DateTime: 0.3
  DateTime::Format::Strptime: 1.0601
  DateTime::Incomplete: 0.02
  Exception::Class: 1.12
  Exception::Class::DBI: 0.94
  Exporter::Tidy: 0.06
  HOP::Lexer: 0.02
  HOP::Parser: 0.01
  HOP::Stream: 0.01
  JSON::Syck: 0.05
  Lingua::EN::Inflect: 0
  Lingua::Strfname: 0.1
  List::MoreUtils: 0
  List::Util: 0
  Locale::Maketext: 1.09
  MIME::Base64: 0
  MIME::Types: 1.14
  OSSP::uuid: 0
  Regexp::Common: 2.119
  Term::ANSIColor: 0
  Widget::Meta: 0.03
  XML::Simple: 2.13
  aliased: 0.11
  version: 0.42
build_requires:
  App::Info: 0.48
  CGI: 3.11
  Class::Trait: 0.11
  FSA::Rules: 0.21
  File::Copy: 0
  File::Path: 0
  Module::Build: 0.27_10
  Pod::Man: 2.08
  Test::Class: 0.1
  Test::Differences: 0.47
  Test::Exception: 0.21
  Test::File: 1.08
  Test::File::Contents: 0.03
  Test::JSON: 0.01
  Test::MockModule: 0.04
  Test::More: 0.17
  Test::NoWarnings: 0.03
  Test::Output: 0.07
  Test::Pod: 1.06
  Test::Pod::Coverage: 0.08
  Test::XML: 0.07
provides:
  Kinetic:
    file: lib/Kinetic.pm
    version: 0.000002
  Kinetic::Build:
    file: lib/Kinetic/Build.pm
    version: 0.000002
  Kinetic::Build::AppInfoHandler:
    file: lib/Kinetic/Build/Base.pm
  Kinetic::Build::Base:
    file: lib/Kinetic/Build/Base.pm
    version: 0.000002
  Kinetic::Build::CroakHandler:
    file: lib/Kinetic/Build/Base.pm
  Kinetic::Build::PrintHandler:
    file: lib/Kinetic/Build/Base.pm
  Kinetic::Build::PromptHandler:
    file: lib/Kinetic/Build/Base.pm
  Kinetic::Build::Schema:
    file: lib/Kinetic/Build/Schema.pm
    version: 0.000002
  Kinetic::Build::Schema::DB:
    file: lib/Kinetic/Build/Schema/DB.pm
    version: 0.000002
  Kinetic::Build::Schema::DB::Pg:
    file: lib/Kinetic/Build/Schema/DB/Pg.pm
    version: 0.000002
  Kinetic::Build::Schema::DB::SQLite:
    file: lib/Kinetic/Build/Schema/DB/SQLite.pm
    version: 0.000002
  Kinetic::Build::Setup:
    file: lib/Kinetic/Build/Setup.pm
    version: 0.000002
  Kinetic::Build::Setup::Cache:
    file: lib/Kinetic/Build/Setup/Cache.pm
    version: 0.000002
  Kinetic::Build::Setup::Cache::File:
    file: lib/Kinetic/Build/Setup/Cache/File.pm
    version: 0.000002
  Kinetic::Build::Setup::Cache::Memcached:
    file: lib/Kinetic/Build/Setup/Cache/Memcached.pm
    version: 0.000002
  Kinetic::Build::Setup::State:
    file: lib/Kinetic/Build/Setup.pm
  Kinetic::Build::Setup::Store:
    file: lib/Kinetic/Build/Setup/Store.pm
    version: 0.000002
  Kinetic::Build::Setup::Store::DB:
    file: lib/Kinetic/Build/Setup/Store/DB.pm
    version: 0.000002
  Kinetic::Build::Setup::Store::DB::Pg:
    file: lib/Kinetic/Build/Setup/Store/DB/Pg.pm
    version: 0.000002
  Kinetic::Build::Setup::Store::DB::SQLite:
    file: lib/Kinetic/Build/Setup/Store/DB/SQLite.pm
    version: 0.000002
  Kinetic::Build::Test:
    file: lib/Kinetic/Build/Test.pm
    version: 0.000002
  Kinetic::DataType::DateTime:
    file: lib/Kinetic/DataType/DateTime.pm
    version: 0.000002
  Kinetic::DataType::DateTime::Incomplete:
    file: lib/Kinetic/DataType/DateTime/Incomplete.pm
    version: 0.000002
  Kinetic::DataType::Duration:
    file: lib/Kinetic/DataType/Duration.pm
    version: 0.000002
  Kinetic::DataType::MediaType:
    file: lib/Kinetic/DataType/MediaType.pm
    version: 0.000002
  Kinetic::DataType::State:
    file: lib/Kinetic/DataType/State.pm
    version: 0.000002
  Kinetic::Express:
    file: lib/Kinetic/Express.pm
    version: 0.000002
  Kinetic::Format:
    file: lib/Kinetic/Format.pm
    version: 0.000002
  Kinetic::Format::JSON:
    file: lib/Kinetic/Format/JSON.pm
    version: 0.000002
  Kinetic::Format::XML:
    file: lib/Kinetic/Format/XML.pm
    version: 0.000002
  Kinetic::Meta:
    file: lib/Kinetic/Meta.pm
    version: 0.000002
  Kinetic::Meta::AccessorBuilder:
    file: lib/Kinetic/Meta/AccessorBuilder.pm
    version: 0.000002
  Kinetic::Meta::Attribute:
    file: lib/Kinetic/Meta/Attribute.pm
    version: 0.000002
  Kinetic::Meta::Attribute::Schema:
    file: lib/Kinetic/Meta/Attribute/Schema.pm
    version: 0.000002
  Kinetic::Meta::Class:
    file: lib/Kinetic/Meta/Class.pm
    version: 0.000002
  Kinetic::Meta::Class::Schema:
    file: lib/Kinetic/Meta/Class/Schema.pm
    version: 0.000002
  Kinetic::Meta::DataTypes:
    file: lib/Kinetic/Meta/DataTypes.pm
    version: 0.000002
  Kinetic::Meta::Method:
    file: lib/Kinetic/Meta/Method.pm
    version: 0.000002
  Kinetic::Meta::Type:
    file: lib/Kinetic/Meta/Type.pm
    version: 0.000002
  Kinetic::Meta::Widget:
    file: lib/Kinetic/Meta/Widget.pm
    version: 0.000002
  Kinetic::Store:
    file: lib/Kinetic/Store.pm
    version: 0.000002
  Kinetic::Store::DB:
    file: lib/Kinetic/Store/DB.pm
    version: 0.000002
  Kinetic::Store::DB::Pg:
    file: lib/Kinetic/Store/DB/Pg.pm
    version: 0.000002
  Kinetic::Store::DB::SQLite:
    file: lib/Kinetic/Store/DB/SQLite.pm
    version: 0.000002
  Kinetic::Store::DB::SQLite::DBI:
    file: lib/Kinetic/Store/DB/SQLite/DBI.pm
    version: 0.000002
  Kinetic::Store::DB::SQLite::DBI::db:
    file: lib/Kinetic/Store/DB/SQLite/DBI.pm
    version: 0.000002
  Kinetic::Store::DB::SQLite::DBI::st:
    file: lib/Kinetic/Store/DB/SQLite/DBI.pm
    version: 0.000002
  Kinetic::Store::DB::mysql:
    file: lib/Kinetic/Store/DB/mysql.pm
    version: 0.000002
  Kinetic::Store::Lexer::Code:
    file: lib/Kinetic/Store/Lexer/Code.pm
    version: 0.000002
  Kinetic::Store::Lexer::String:
    file: lib/Kinetic/Store/Lexer/String.pm
    version: 0.000002
  Kinetic::Store::Parser:
    file: lib/Kinetic/Store/Parser.pm
    version: 0.000002
  Kinetic::Store::Search:
    file: lib/Kinetic/Store/Search.pm
    version: 0.000002
  Kinetic::Util::Cache:
    file: lib/Kinetic/Util/Cache.pm
    version: 0.000002
  Kinetic::Util::Cache::File:
    file: lib/Kinetic/Util/Cache/File.pm
    version: 0.000002
  Kinetic::Util::Cache::Memcached:
    file: lib/Kinetic/Util/Cache/Memcached.pm
    version: 0.000002
  Kinetic::Util::Collection:
    file: lib/Kinetic/Util/Collection.pm
    version: 0.000002
  Kinetic::Util::Config:
    file: lib/Kinetic/Util/Config.pm
    version: 0.000002
  Kinetic::Util::Constants:
    file: lib/Kinetic/Util/Constants.pm
    version: 0.000002
  Kinetic::Util::Context:
    file: lib/Kinetic/Util/Context.pm
    version: 0.000002
  Kinetic::Util::Exception:
    file: lib/Kinetic/Util/Exceptions.pm
  Kinetic::Util::Exception::DBI:
    file: lib/Kinetic/Util/Exceptions.pm
  Kinetic::Util::Exception::DBI::DBH:
    file: lib/Kinetic/Util/Exceptions.pm
  Kinetic::Util::Exception::DBI::DRH:
    file: lib/Kinetic/Util/Exceptions.pm
  Kinetic::Util::Exception::DBI::H:
    file: lib/Kinetic/Util/Exceptions.pm
  Kinetic::Util::Exception::DBI::STH:
    file: lib/Kinetic/Util/Exceptions.pm
  Kinetic::Util::Exception::DBI::Unknown:
    file: lib/Kinetic/Util/Exceptions.pm
  Kinetic::Util::Exceptions:
    file: lib/Kinetic/Util/Exceptions.pm
    version: 0.000002
  Kinetic::Util::Functions:
    file: lib/Kinetic/Util/Functions.pm
    version: 0.000002
  Kinetic::Util::Iterator:
    file: lib/Kinetic/Util/Iterator.pm
    version: 0.000002
  Kinetic::Util::Language:
    file: lib/Kinetic/Util/Language.pm
    version: 0.000002
  Kinetic::Util::Language::en:
    file: lib/Kinetic/Util/Language/en.pm
    version: 0.000002
  Kinetic::Util::Language::en_uk:
    file: lib/Kinetic/Util/Language/en_uk.pm
    version: 0.000002
  Kinetic::Util::Language::en_us:
    file: lib/Kinetic/Util/Language/en_us.pm
    version: 0.000002
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
