--- #YAML:1.0
name: App-Kinetic
version: 0.0.1
author:
  - Kineticode, Inc. <info@kineticode.com>
abstract: The Kinetic enterprise application framework
license: perl
provides:
  Kinetic:
    file: lib/App/Kinetic.pm
    version: 0.0.1
generated_by: Module::Build version 0.26
