---
name: Object-Relation
version: !!perl/hash:Module::Build::Version
  original: !!perl/hash:version
    qv: 1
    version:
      - 0
      - 0
      - 2
  qv: 1
  version:
    - 0
    - 0
    - 2
author:
  - 'Kineticode, Inc. <info@obj_relode.com>'
abstract: Advanced Object Relational Mapper
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Array::AsHash: 0.31
  Class::BuildMethods: 0.1
  Class::Meta: 0.53
  Class::Meta::Express: 0.03
  Clone: 0.15
  DBI: 1.5
  Data::Types: 0.06
  DateTime: 0.3
  DateTime::Format::Strptime: 1.0601
  DateTime::Incomplete: 0.02
  Exception::Class: 1.12
  Exception::Class::DBI: 0.94
  Exporter::Tidy: 0.06
  FSA::Rules: 0.25
  File::Find::Rule: 0
  HOP::Lexer: 0.02
  HOP::Parser: 0.01
  HOP::Stream: 0.01
  JSON::Syck: 0.05
  Lingua::EN::Inflect: 0
  List::MoreUtils: 0
  List::Util: 0
  Locale::Maketext: 1.09
  MIME::Base64: 0
  MIME::Types: 1.14
  OSSP::uuid: 0
  Regexp::Common: 2.119
  Widget::Meta: 0.03
  XML::Simple: 2.13
  aliased: 0.11
  version: 0.42
build_requires:
  App::Info: 0.48
  Cache::Cache: 1.04
  Class::Trait: 0.11
  DBD::SQLite: 1.12
  File::Path: 0
  Module::Build: 0.28
  Pod::Man: 2.08
  Test::Class: 0.1
  Test::Differences: 0.47
  Test::Exception: 0.21
  Test::File: 1.08
  Test::File::Contents: 0.03
  Test::JSON: 0.01
  Test::MockModule: 0.04
  Test::More: 0.17
  Test::NoWarnings: 0.03
  Test::Output: 0.07
  Test::XML: 0.07
provides:
  Object::Relation:
    file: lib/Object/Relation.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Base:
    file: lib/Object/Relation/Base.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Cache:
    file: lib/Object/Relation/Cache.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Cache::File:
    file: lib/Object/Relation/Cache/File.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Cache::Memcached:
    file: lib/Object/Relation/Cache/Memcached.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Collection:
    file: lib/Object/Relation/Collection.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::DataType::DateTime:
    file: lib/Object/Relation/DataType/DateTime.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::DataType::DateTime::Incomplete:
    file: lib/Object/Relation/DataType/DateTime/Incomplete.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::DataType::Duration:
    file: lib/Object/Relation/DataType/Duration.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::DataType::MediaType:
    file: lib/Object/Relation/DataType/MediaType.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::DataType::State:
    file: lib/Object/Relation/DataType/State.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Exception:
    file: lib/Object/Relation/Exceptions.pm
  Object::Relation::Exception::DBI:
    file: lib/Object/Relation/Exceptions.pm
  Object::Relation::Exception::DBI::DBH:
    file: lib/Object/Relation/Exceptions.pm
  Object::Relation::Exception::DBI::DRH:
    file: lib/Object/Relation/Exceptions.pm
  Object::Relation::Exception::DBI::H:
    file: lib/Object/Relation/Exceptions.pm
  Object::Relation::Exception::DBI::STH:
    file: lib/Object/Relation/Exceptions.pm
  Object::Relation::Exception::DBI::Unknown:
    file: lib/Object/Relation/Exceptions.pm
  Object::Relation::Exceptions:
    file: lib/Object/Relation/Exceptions.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Format:
    file: lib/Object/Relation/Format.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Format::JSON:
    file: lib/Object/Relation/Format/JSON.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Format::XML:
    file: lib/Object/Relation/Format/XML.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Functions:
    file: lib/Object/Relation/Functions.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Handle:
    file: lib/Object/Relation/Handle.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Handle::DB:
    file: lib/Object/Relation/Handle/DB.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Handle::DB::Pg:
    file: lib/Object/Relation/Handle/DB/Pg.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Handle::DB::SQLite:
    file: lib/Object/Relation/Handle/DB/SQLite.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Handle::DB::SQLite::DBI:
    file: lib/Object/Relation/Handle/DB/SQLite/DBI.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Handle::DB::SQLite::DBI::db:
    file: lib/Object/Relation/Handle/DB/SQLite/DBI.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Handle::DB::SQLite::DBI::st:
    file: lib/Object/Relation/Handle/DB/SQLite/DBI.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Iterator:
    file: lib/Object/Relation/Iterator.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Language:
    file: lib/Object/Relation/Language.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Language::en:
    file: lib/Object/Relation/Language/en.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Language::en_uk:
    file: lib/Object/Relation/Language/en_uk.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Language::en_us:
    file: lib/Object/Relation/Language/en_us.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Lexer::Code:
    file: lib/Object/Relation/Lexer/Code.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Lexer::String:
    file: lib/Object/Relation/Lexer/String.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Meta:
    file: lib/Object/Relation/Meta.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Meta::AccessorBuilder:
    file: lib/Object/Relation/Meta/AccessorBuilder.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Meta::Attribute:
    file: lib/Object/Relation/Meta/Attribute.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Meta::Attribute::Schema:
    file: lib/Object/Relation/Meta/Attribute/Schema.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Meta::Class:
    file: lib/Object/Relation/Meta/Class.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Meta::Class::Schema:
    file: lib/Object/Relation/Meta/Class/Schema.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Meta::DataTypes:
    file: lib/Object/Relation/Meta/DataTypes.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Meta::Method:
    file: lib/Object/Relation/Meta/Method.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Meta::Type:
    file: lib/Object/Relation/Meta/Type.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Meta::Widget:
    file: lib/Object/Relation/Meta/Widget.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Parser:
    file: lib/Object/Relation/Parser.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Schema:
    file: lib/Object/Relation/Schema.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Schema::DB:
    file: lib/Object/Relation/Schema/DB.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Schema::DB::Pg:
    file: lib/Object/Relation/Schema/DB/Pg.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Schema::DB::SQLite:
    file: lib/Object/Relation/Schema/DB/SQLite.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Search:
    file: lib/Object/Relation/Search.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Setup:
    file: lib/Object/Relation/Setup.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Setup::DB:
    file: lib/Object/Relation/Setup/DB.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Setup::DB::Pg:
    file: lib/Object/Relation/Setup/DB/Pg.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Object::Relation::Setup::DB::SQLite:
    file: lib/Object/Relation/Setup/DB/SQLite.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
generated_by: Module::Build version 0.2804
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
