---
name: Kinetic
version: !!perl/hash:Module::Build::Version
  original: !!perl/hash:version
    qv: 1
    version:
      - 0
      - 0
      - 2
  qv: 1
  version:
    - 0
    - 0
    - 2
author:
  - 'Kineticode, Inc. <info@kineticode.com>'
abstract: The Kinetic enterprise application framework
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Array::AsHash: 0.31
  Class::BuildMethods: 0.1
  Class::Meta: 0.53
  Class::Meta::Express: 0.03
  Clone: 0.15
  DBI: 1.5
  Data::Types: 0.06
  DateTime: 0.3
  DateTime::Format::Strptime: 1.0601
  DateTime::Incomplete: 0.02
  Exception::Class: 1.12
  Exception::Class::DBI: 0.94
  Exporter::Tidy: 0.06
  FSA::Rules: 0.25
  File::Find::Rule: 0
  HOP::Lexer: 0.02
  HOP::Parser: 0.01
  HOP::Stream: 0.01
  JSON::Syck: 0.05
  Lingua::EN::Inflect: 0
  List::MoreUtils: 0
  List::Util: 0
  Locale::Maketext: 1.09
  MIME::Base64: 0
  MIME::Types: 1.14
  OSSP::uuid: 0
  Regexp::Common: 2.119
  Term::ANSIColor: 0
  Widget::Meta: 0.03
  XML::Simple: 2.13
  aliased: 0.11
  version: 0.42
build_requires:
  App::Info: 0.48
  Cache::Cache: 1.04
  Class::Trait: 0.11
  DBD::SQLite: 1.12
  File::Copy: 0
  File::Path: 0
  Module::Build: 0.28
  Pod::Man: 2.08
  Test::Class: 0.1
  Test::Differences: 0.47
  Test::Exception: 0.21
  Test::File: 1.08
  Test::File::Contents: 0.03
  Test::JSON: 0.01
  Test::MockModule: 0.04
  Test::More: 0.17
  Test::NoWarnings: 0.03
  Test::Output: 0.07
  Test::XML: 0.07
provides:
  Kinetic:
    file: lib/Kinetic.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Build:
    file: lib/Kinetic/Build.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Build::AppInfoHandler:
    file: lib/Kinetic/Build.pm
  Kinetic::Build::CroakHandler:
    file: lib/Kinetic/Build.pm
  Kinetic::Build::PrintHandler:
    file: lib/Kinetic/Build.pm
  Kinetic::Build::PromptHandler:
    file: lib/Kinetic/Build.pm
  Kinetic::Build::Setup:
    file: lib/Kinetic/Build/Setup.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Build::Setup::State:
    file: lib/Kinetic/Build/Setup.pm
  Kinetic::Build::Setup::Store:
    file: lib/Kinetic/Build/Setup/Store.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Build::Setup::Store::DB:
    file: lib/Kinetic/Build/Setup/Store/DB.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Build::Setup::Store::DB::Pg:
    file: lib/Kinetic/Build/Setup/Store/DB/Pg.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Build::Setup::Store::DB::SQLite:
    file: lib/Kinetic/Build/Setup/Store/DB/SQLite.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Express:
    file: lib/Kinetic/Express.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Cache:
    file: lib/Kinetic/Store/Cache.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Cache::File:
    file: lib/Kinetic/Store/Cache/File.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Cache::Memcached:
    file: lib/Kinetic/Store/Cache/Memcached.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Collection:
    file: lib/Kinetic/Store/Collection.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::DataType::DateTime:
    file: lib/Kinetic/Store/DataType/DateTime.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::DataType::DateTime::Incomplete:
    file: lib/Kinetic/Store/DataType/DateTime/Incomplete.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::DataType::Duration:
    file: lib/Kinetic/Store/DataType/Duration.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::DataType::MediaType:
    file: lib/Kinetic/Store/DataType/MediaType.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::DataType::State:
    file: lib/Kinetic/Store/DataType/State.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Exception:
    file: lib/Kinetic/Store/Exceptions.pm
  Kinetic::Store::Exception::DBI:
    file: lib/Kinetic/Store/Exceptions.pm
  Kinetic::Store::Exception::DBI::DBH:
    file: lib/Kinetic/Store/Exceptions.pm
  Kinetic::Store::Exception::DBI::DRH:
    file: lib/Kinetic/Store/Exceptions.pm
  Kinetic::Store::Exception::DBI::H:
    file: lib/Kinetic/Store/Exceptions.pm
  Kinetic::Store::Exception::DBI::STH:
    file: lib/Kinetic/Store/Exceptions.pm
  Kinetic::Store::Exception::DBI::Unknown:
    file: lib/Kinetic/Store/Exceptions.pm
  Kinetic::Store::Exceptions:
    file: lib/Kinetic/Store/Exceptions.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Format:
    file: lib/Kinetic/Store/Format.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Format::JSON:
    file: lib/Kinetic/Store/Format/JSON.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Format::XML:
    file: lib/Kinetic/Store/Format/XML.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Functions:
    file: lib/Kinetic/Store/Functions.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Handle:
    file: lib/Kinetic/Store/Handle.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Handle::DB:
    file: lib/Kinetic/Store/Handle/DB.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Handle::DB::Pg:
    file: lib/Kinetic/Store/Handle/DB/Pg.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Handle::DB::SQLite:
    file: lib/Kinetic/Store/Handle/DB/SQLite.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Handle::DB::SQLite::DBI:
    file: lib/Kinetic/Store/Handle/DB/SQLite/DBI.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Handle::DB::SQLite::DBI::db:
    file: lib/Kinetic/Store/Handle/DB/SQLite/DBI.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Handle::DB::SQLite::DBI::st:
    file: lib/Kinetic/Store/Handle/DB/SQLite/DBI.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Handle::DB::mysql:
    file: lib/Kinetic/Store/Handle/DB/mysql.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Iterator:
    file: lib/Kinetic/Store/Iterator.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Language:
    file: lib/Kinetic/Store/Language.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Language::en:
    file: lib/Kinetic/Store/Language/en.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Language::en_uk:
    file: lib/Kinetic/Store/Language/en_uk.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Language::en_us:
    file: lib/Kinetic/Store/Language/en_us.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Lexer::Code:
    file: lib/Kinetic/Store/Lexer/Code.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Lexer::String:
    file: lib/Kinetic/Store/Lexer/String.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Meta:
    file: lib/Kinetic/Store/Meta.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Meta::AccessorBuilder:
    file: lib/Kinetic/Store/Meta/AccessorBuilder.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Meta::Attribute:
    file: lib/Kinetic/Store/Meta/Attribute.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Meta::Attribute::Schema:
    file: lib/Kinetic/Store/Meta/Attribute/Schema.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Meta::Class:
    file: lib/Kinetic/Store/Meta/Class.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Meta::Class::Schema:
    file: lib/Kinetic/Store/Meta/Class/Schema.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Meta::DataTypes:
    file: lib/Kinetic/Store/Meta/DataTypes.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Meta::Method:
    file: lib/Kinetic/Store/Meta/Method.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Meta::Type:
    file: lib/Kinetic/Store/Meta/Type.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Meta::Widget:
    file: lib/Kinetic/Store/Meta/Widget.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Parser:
    file: lib/Kinetic/Store/Parser.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Schema:
    file: lib/Kinetic/Store/Schema.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Schema::DB:
    file: lib/Kinetic/Store/Schema/DB.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Schema::DB::Pg:
    file: lib/Kinetic/Store/Schema/DB/Pg.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Schema::DB::SQLite:
    file: lib/Kinetic/Store/Schema/DB/SQLite.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Search:
    file: lib/Kinetic/Store/Search.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Setup:
    file: lib/Kinetic/Store/Setup.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Setup::DB:
    file: lib/Kinetic/Store/Setup/DB.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Setup::DB::Pg:
    file: lib/Kinetic/Store/Setup/DB/Pg.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
  Kinetic::Store::Setup::DB::SQLite:
    file: lib/Kinetic/Store/Setup/DB/SQLite.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 0
        - 0
        - 2
generated_by: Module::Build version 0.2804
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
