package Kinetic::Meta::Method;

# $Id$

use strict;

use version;
our $VERSION = version->new('0.0.2');

use base 'Class::Meta::Method';

=head1 Name

Kinetic::Meta::Method - Kinetic object method introspection

=head1 Synopsis

  # Assuming MyThingy was generated by Kinetic::Meta.
  my $class  = MyThingy->my_class;
  my $thingy = MyThingy->new;

  print "\nMethods:\n";
  for my $meth ($class->methods) {
      print "  o ", $meth->name, $/;
      $meth->call($thingy);
  }

=head1 Description

This class inherits from L<Class::Meta::Method|Class::Meta::Method> to provide
method metadata for Kinetic classes. See the L<Class::Meta|Class:Meta>
documentation for details on meta classes. See the L<"Instance Interface">
section for the attributes added to Kinetic::Meta::Method in addition to those
defined by Class::Meta::Method.

=cut

##############################################################################
# Instance Methods.
##############################################################################

=head1 Instance Interface

=head2 Accessor Methods

=head3 delegates_to

  my $delegates_to = $meth->delegates_to;

If the method transparently delegates to an object of another class, this
method will return the Kinetic::Meta::Class object describing that class. This
method is implicitly set by Kinetic::Meta for classes that either extend or
mediate another class, or are a type of another class. In those cases,
Kinetic::Meta will create extra methods to delegate to the methods of the
referenced or extended classes, and those methods will have their
C<delegates_to> methods set accordingly.

=cut

sub delegates_to { shift->{delegates_to} }

##############################################################################

=head3 acts_as

  my $acts_as = $meth->acts_as;

If C<delegates_to()> returns a Kinetic::Meta::Class object representing the
class of object to which the method delegates, C<acts_as()> returns the
Kinetic::Meta::Method object to which this method corresponds. That is, this
method I<acts as> the method returned here.

=cut

sub acts_as { shift->{acts_as} }

1;
__END__

##############################################################################

=head1 Copyright and License

Copyright (c) 2004-2006 Kineticode, Inc. <info@kineticode.com>

This work is made available under the terms of Version 2 of the GNU General
Public License. You should have received a copy of the GNU General Public
License along with this program; if not, download it from
L<http://www.gnu.org/licenses/gpl.txt> or write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

This work is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE. See the GNU General Public License Version 2 for more
details.

=cut
